// asciidoctor -r asciidoctor-diagram master .adoc

# Kafka internals
Tom Bentley
:toc: left  
:toclevels: 4
:source-highlighter: pygments
:icons: font
:seqdiag-fontpath: /usr/share/fonts/truetype/inconsolata/Inconsolata-Regular.ttf

:leveloffset: +1

This document is about the _implementation_ of Apache Kafka.
It does not address why you might want to use Kafka, or how to do anything in particular with it.
Instead it discusses both the protocol and the code in depth. 
It is largely aimed as answering the question "How does Kafka work?".
It assumes you have some familiarity with Kafka concepts such as topics, partitions, replicas, logs and segments.

The content is broken into three parts. 
First the Kafka protocol is introduced, mostly without talking about implementation details.
Second we talk about the implementation of the Apache Kafka clients, broker and other things.
Finally we try to put this theoretical knowledge to use by talking about how it relates to real problems.

# The Kafka Protocol

In this part we cover most of the Kafka protocol in the abstract.
We're not concerned here with how messages get serialized, networking, threading or any other implementation concerns.
This is purely about what information flows between which peers, and what they might do with it.


:leveloffset: +1

include::protocol-overview.adoc[]

include::bootstrap.adoc[]

include::producer.adoc[]

include::consumer.adoc[]

include::broker.adoc[]

include::admin-client.adoc[]

include::controller.adoc[]

:leveloffset: -1

//
## Kafka Connect
//
## Kafka Streams
//
